### ISSUE TITLE
[APP REQUEST] Linkwarden

### ISSUE THREAD

**Issue by aWalrus** [meienberger/runtipi-appstore#1022]
**Describe app**
"_Linkwarden is a fully self-hostable, open-source collaborative bookmark manager to collect, organize and archive webpages._"
A bookmark manager that supports organizing and collaborating with a reasonably pretty interface.

**Links**
Repository: https://github.com/linkwarden/linkwarden
Webpage: http://linkwarden.app/
Guide to self-hosting: https://docs.linkwarden.app/getting-started/self-hosting

**Additional context**
Appears to be a reasonable alternative to apps like raindrop.io. The archiving part is related to ArchiveBox (#377).

**Comment by DrMxrcy** [comment]
Added in #1083!
