### ISSUE TITLE
[APP REQUEST] Audiobookshelf

### ISSUE THREAD

**Issue by Porroe** [meienberger/runtipi-appstore#1060]
**Describe app**
Audiobookshelf is a self-hosted audiobook and podcast server with Android and iOS apps.

**Links**

- Repository: https://github.com/advplyr/audiobookshelf
- Webpage: https://www.audiobookshelf.org/
- Guide to self-hosting: https://www.audiobookshelf.org/docs#docker-install

**Additional context**

- A good alternative to BookSonic with open source mobile apps for Android and iOS. Includes Android Auto support.
- Available in Umbrel.

**Comment by DrMxrcy** [comment]
Added in #1065!
