### ISSUE TITLE
Invidious install failed

### ISSUE THREAD

**Issue by jacobthetechy** [meienberger/runtipi-appstore#1089]
I recently did a fresh install to the latest version 1.6.0 and trying to install app's that I have been using. Invidious is one that I am currently having issues with. This is the output of the logs after failing to install.

```shell
tail -n 0 -f logs/error.log 
2023-08-28T21:26:19.918Z - error > 	An error occurred: Command failed: docker compose --env-file /root/runtipi/app-data/invidious/app.env --projed
 Container invidious-db  Starting
 Container invidious-db  Started
 Container invidious-db  Waiting
 Container invidious-db  Error
dependency failed to start: container invidious-db is unhealthy

2023-08-28T21:26:19.921Z > Failed to install app invidious: Command failed: docker compose --env-file /root/runtipi/app-data/invidious/app.env --projd
 Container invidious-db  Starting
 Container invidious-db  Started
 Container invidious-db  Waiting
 Container invidious-db  Error
dependency failed to start: container invidious-db is unhealthy

2023-08-28T21:26:19.922Z > server error: Failed to install app invidious, see logs for more details
```

Any insight on what I need to do to get this to work?

Thanks!

**Comment by meienberger** [comment]
Hello there is a bug in the latest release with extra files. We are rolling out a fix soon, can you try in the meantime:
`sudo find ./app-data/invidious/data -name .gitkeep -delete`

**Comment by jacobthetechy** [comment]
That did not seem to work. But upgrading to runtipi 2.0.0 did fix the issue.

Thanks.
