### ISSUE TITLE
[APP REQUEST]NasTool

### ISSUE THREAD

**Issue by polo2013** [meienberger/runtipi-appstore#167]
Have you considered adding the app yourself? 

**Describe app**
媒体库资源归集、整理自动化工具

**Links**
[Nastool github
](https://github.com/jxxghp/nas-tools)

**Comment by meienberger** [comment]
I don't understand Chinese so this will be rather difficult to add

**Comment by DrMxrcy** [comment]
Missing Repo. Closing
