### ISSUE TITLE
Grocy admin login

### ISSUE THREAD

**Issue by jacobthetechy** [meienberger/runtipi-appstore#182]
Was only able to log into Grocy by a pure guess that the admin page was admin/admin. Could this be added into its page when installed?

**Comment by meienberger** [comment]
Thank you fixed in this [commit](https://github.com/meienberger/runtipi-appstore/commit/b7d9993be07d4dc2755b893c4975031304f6af6e)

**Comment by jacobthetechy** [comment]
Thanks!
