### ISSUE TITLE
Giteat error when app is exposed

### ISSUE THREAD

**Issue by jacobthetechy** [meienberger/runtipi-appstore#183]
When exposing Gitea there is an error banner when going to the page.

> Your ROOT_URL in app.ini is http://localhost:8108/ but you are visiting https://exposed.url.com/
> You should set ROOT_URL correctly, otherwise the web may not work correctly.

**Comment by meienberger** [comment]
This is because Tipi does not yet support automatic variable replacement in config files (currently only in docker files) you'll need to update `app.ini` manually in your data folder (`runtipi/app-data/gitea`)
