### ISSUE TITLE
[APP REQUEST] Haven

### ISSUE THREAD

**Issue by mawise** [meienberger/runtipi-appstore#29]
**Describe app**
Haven is a self hosted private blog and feed reader you can use instead of facebook.

**Links**
https://havenweb.org/
https://github.com/havenweb/haven

**Additional context**
Screenshots: https://havenweb.org/screenshots.html
Container Images: 
https://github.com/havenweb/haven/pkgs/container/haven
MIT License

**Comment by meienberger** [comment]
Hello, I saw you are the maintainer of Haven. I'm currently working on adding it and wanted to know if you got any logo available? I couldn't find one

**Comment by meienberger** [comment]
App added
