### ISSUE TITLE
[APP REQUEST] Librephotos

### ISSUE THREAD

**Issue by tandy-1000** [meienberger/runtipi-appstore#30]
**Describe app**
>A self-hosted open source photo management service.

LibrePhotos has a number of features PhotoPrism doesn't.

**Links**
- [Feature comparison](https://docs.librephotos.com/2/features/)
- https://github.com/LibrePhotos/librephotos

**Comment by meienberger** [comment]
Hello, thanks for your request. Currently LibrePhotos has a limitation to run inside Tipi. I have opened an issue on their repo [here](https://github.com/LibrePhotos/librephotos-docker/issues/72) Will add the app once it is fixed

**Comment by tandy-1000** [comment]
Thank you!

**Comment by meienberger** [comment]
Turns out it was my limitation to correctly read the doc haha

**Comment by meienberger** [comment]
Added to the app store!

**Comment by tandy-1000** [comment]
Thanks so much!
