### ISSUE TITLE
[APP REQUEST] Paperless-ngx

### ISSUE THREAD

**Issue by tandy-1000** [meienberger/runtipi-appstore#31]
**Describe app**
>A community-supported supercharged version of paperless: scan, index and archive all your physical documents.

Paperless is a very popular web app to help manage paper documents.

**Links**
https://github.com/paperless-ngx/paperless-ngx

**Comment by sclaren** [comment]
I just made an integration and started a pull for this. Paperless + TiKA + Gotenberg ;)

**Comment by DrMxrcy** [comment]
Added in #392!
