### ISSUE TITLE
[APP REQUEST] ChatGPT-UI

### ISSUE THREAD

**Issue by innocentius** [meienberger/runtipi-appstore#315]
Have you considered adding the app yourself? 
(Yes, but I don't have the time unfortunately, and I can wait)

**Describe app**
A ChatGPT web client that supports multiple users, multiple database connections for persistent data storage, supports i18n. Provides Docker images and quick deployment scripts.

**Links**
https://github.com/WongSaang/chatgpt-ui

**Comment by meienberger** [comment]
Hello, this would be a great addition in our app store

**Comment by innocentius** [comment]
Not sure why this one is chosen, it doesn't have a login system, don't save any chat log, and user need to enter api-key each time they change a browser. The app is basically a trail app with no extended functionality, and is basically useless if the server is exposed to the internet, but if it is your choice it is your choice...

**Comment by meienberger** [comment]
We'll add the other ones too

**Comment by DrMxrcy** [comment]
Working on ChatGPT UI in #339!

**Comment by DrMxrcy** [comment]
ChatGPT UI tested and added #339!
