### ISSUE TITLE
[APP REQUEST] Nocodb

### ISSUE THREAD

**Issue by revitteth** [meienberger/runtipi-appstore#32]
**Describe app**
No code open source airtable alternative. Exposes easy ui over postgres mysql etc. 

**Links**
- https://www.nocodb.com/
- https://github.com/nocodb/nocodb
- https://github.com/NocoDB/NocoDB/blob/develop/LICENSE

**Additional context**
Looks pretty good!

**Comment by DrMxrcy** [comment]
I opened up #201 to add it

**Comment by meienberger** [comment]
Merged
