### ISSUE TITLE
[APP REQUEST] Plausible.io

### ISSUE THREAD

**Issue by iamNairda** [meienberger/runtipi-appstore#345]
**Describe app**
I know there is Umami, but I believe it is good to have variety, so everyone can decide for themselves, which the ideal app is.
Plausible is intuitive, lightweight and open source web analytics. No cookies and fully compliant with GDPR, CCPA and PECR.

**Links**
https://plausible.io/
https://github.com/plausible/analytics

**Additional context**
n/a

**Comment by DrMxrcy** [comment]
Added! #475
