### ISSUE TITLE
[APP REQUEST] SearX (SearXNG)

### ISSUE THREAD

**Issue by radonn24** [meienberger/runtipi-appstore#38]
**Describe app**

Privacy-respecting metasearch engine.

Searx is a free internet metasearch engine which aggregates results from more than 70 search services. Users are neither tracked nor profiled. Additionally, searx can be used over Tor for online anonymity.

**Links**
Documentation: https://searx.github.io/searx/
Wiki: https://github.com/searx/searx/wiki
Source code: https://github.com/searx/searx
docker-compose files: https://github.com/searxng/searxng-docker

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by sethforprivacy** [comment]
Already PR'd 😄 

https://github.com/meienberger/runtipi-appstore/pull/10

**Comment by radonn24** [comment]
Ahh! Thank you! I checked the PR list, but didn't see it ... I must have overlooked it!
