### ISSUE TITLE
[APP REQUEST] Duplicati

### ISSUE THREAD

**Issue by Samurai1201** [meienberger/runtipi-appstore#40]
Duplicati is a backup solution that includes many ways to backup and encrypt your data.
It would be helpful as a way to run an offsite backup for your data and setup config.

https://www.duplicati.com/
https://github.com/duplicati/duplicati

Duplicati supports: Amazon S3, IDrive e2, Backblaze (B2), Box, Dropbox, FTP, Google Cloud and Drive, HubiC, MEGA, Microsoft Azure and OneDrive, Rackspace Cloud Files, OpenStack Storage (Swift), Sia, Storj DCS, SSH (SFTP), WebDAV, Tencent Cloud Object Storage (COS), …

**Comment by cygairko** [comment]
IMHO this might be a good approach to provide volume backup solution for runtipi.

**Comment by meienberger** [comment]
Thanks for your suggestion, it is quite hard for me to keep up with all the app requests. Would be glad if someone could open a PR guide [here](https://github.com/meienberger/runtipi/wiki/Adding-your-own-app)

**Comment by suodrazah** [comment]
I'm planning on adding duplicati, unless someone beats me to it. Was hoping to get to it earlier than now but the last month has been unusually demanding elsewhere. I use duplicati heavily across dozens of servers and have a good understanding of how it behaves. It should work well here but is less than ideal for heavier databases wherein you might consider sqlbak or something similar.

**Comment by DrMxrcy** [comment]
#226 is now opened!
