### ISSUE TITLE
[APP REQUEST] Simplex-Chat

### ISSUE THREAD

**Issue by NunyaBiznus** [meienberger/runtipi-appstore#480]
**Describe app**
A private & encrypted open-source messenger without any user IDs. All messages are end-to-end encrypted using open-source double-ratchet protocol; the messages are delivered via relay servers using open-source SimpleX Messaging Protocol.

**Links**
Github: https://github.com/simplex-chat/simplexmq
Website: https://simplex.chat

**Comment by DrMxrcy** [comment]
Adding the Simplex SMP server in #540

**Comment by DrMxrcy** [comment]
Added! #540

**Comment by NunyaBiznus** [comment]
Awesome, thank you!
