### ISSUE TITLE
[APP REQUEST] Lidarr

### ISSUE THREAD

**Issue by andrewbrereton** [meienberger/runtipi-appstore#59]
**Describe app**

Lidarr is a music collection manager for Usenet and BitTorrent users. It complements Sonarr, Radarr and Readarr.

**Links**

* Website: https://lidarr.audio/
* GitHub: https://github.com/Lidarr/Lidarr
* License: https://github.com/Lidarr/Lidarr/blob/develop/LICENSE.md
* Installation (including Docker instructions): https://wiki.servarr.com/lidarr/installation

**Comment by meienberger** [comment]
#60
