### ISSUE TITLE
[APP REQUEST] Baikal as a CalDav/CardDav service

### ISSUE THREAD

**Issue by nudeldudel** [meienberger/runtipi-appstore#602]
Instead of the big Nextcloud, I suggest the Sabre.io Baikal CalDav/CarDav-Service for Docker, shown here:

https://github.com/ckulka/baikal-docker

Maybe it is a sensefull alternative for pepole with small resources.

**Comment by YellowWords** [comment]
I'm also just using my Nextcloud instance as a CalDAV / CardAV server at the moment, which it's hilariously bloated for. I may take a stab at making an app for Baikal if I have the time.

**Comment by nudeldudel** [comment]
That would be great!

YellowWords ***@***.***> schrieb am Sa., 15. Juli 2023, 14:24:

**Comment by DireMunchkin** [comment]
I got around to adding Baikal now!
