### ISSUE TITLE
Vaultwaden requires HTTPS

### ISSUE THREAD

**Issue by k3tan172** [meienberger/runtipi-appstore#7]
You can't create an account or use the browser extensions without Vaultwarden being served via HTTPS.
https://github.com/dani-garcia/vaultwarden/wiki/Enabling-HTTPS

**Comment by meienberger** [comment]
Hello, yes Vaultwarden will not work without HTTPS and an SSL certificate. It is out of our power to make it possible. If you want to use it through Tipi you'll have to link a domain name to the app. You can do so directly from the dashboard
