### ISSUE TITLE
[APP REQUEST] homebridge

### ISSUE THREAD

**Issue by roger-richards** [meienberger/runtipi-appstore#894]
**Describe app**
Homebridge is a lightweight NodeJS server you can run on your home network that emulates the iOS HomeKit API. It supports Plugins, which are community-contributed modules that provide a basic bridge from HomeKit to various 3rd-party APIs provided by manufacturers of "smart home" devices.

**Links**
(https://github.com/homebridge/homebridge)

**Additional context**
lots of users and support by home automation geeks worldwide

**Comment by steveiliop56** [comment]
Isn't this already on the run tipi appstore?

**Comment by DrMxrcy** [comment]
Added #1112!

**Comment by roger-richards** [comment]
Thank You!
